gems:
  - buildr-bnd = 0.0.5
  - buildr-iidea = 0.0.9

repositories:
  remote:
    - http://www.stocksoftware.com.au/repositories/external

artifacts:
  asm: asm:asm-all:jar:3.3
  jdom: org.jdom:jdom:jar:1.1
