artifacts:
  asm: asm:asm-all:jar:3.3
  jdom: org.jdom:jdom:jar:1.1

repositories:
  remote:
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://repo1.maven.org/
  release_to:
    url: http://repo.fire.dse.vic.gov.au/content/repositories/releases/
    username: upload
